import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";

export type CustomerReportExportData = {
  generatedAt: string;
  generatedBy: string;
  companyName: string;
  dateRange: string;
  rows: string[][];
};

const HEADERS = ["Srl", "Customer Name", "Contact Person", "Mobile", "Email", "Address"];

const fileDate = () => {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const day = String(now.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
};

const filterText = (data: CustomerReportExportData) =>
  `Company Name: ${data.companyName}, Date: ${data.dateRange}`;

export const downloadCustomerReportPdf = (data: CustomerReportExportData) => {
  const pdf = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  pdf.text("Customer Details Report", 42, 48);
  pdf.setFontSize(10);
  pdf.text(`Generated on: ${data.generatedAt}`, 42, 76);
  pdf.text(`Generated by: ${data.generatedBy}`, 42, 92);
  pdf.text("Applied filters:", 42, 122);
  pdf.setFont("helvetica", "normal");
  pdf.text(filterText(data), 42, 138);

  const body = data.rows.length
    ? data.rows
    : [[{ content: "No data", colSpan: HEADERS.length, styles: { halign: "center" } }]];

  autoTable(pdf, {
    startY: 162,
    head: [HEADERS],
    body: body as any,
    theme: "grid",
    styles: { fontSize: 8, cellPadding: 6, lineColor: [220, 226, 232], lineWidth: 0.5 },
    headStyles: { fillColor: [45, 137, 190], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  pdf.save(`Customer_Details_Report_${fileDate()}.pdf`);
};

export const downloadCustomerReportExcel = (data: CustomerReportExportData) => {
  const sheetRows: (string | number)[][] = [
    ["Customer Details Report"],
    [`Generated on: ${data.generatedAt}`],
    [`Generated by: ${data.generatedBy}`],
    ["Applied filters:"],
    [filterText(data)],
    [],
    HEADERS,
    ...(data.rows.length ? data.rows : [["No data", "", "", "", "", ""]]),
  ];
  const sheet = XLSX.utils.aoa_to_sheet(sheetRows);
  sheet["!merges"] = [
    XLSX.utils.decode_range("A1:F1"),
    XLSX.utils.decode_range("A2:F2"),
    XLSX.utils.decode_range("A3:F3"),
    XLSX.utils.decode_range("A4:F4"),
    XLSX.utils.decode_range("A5:F5"),
  ];
  sheet["!cols"] = [
    { wch: 8 },
    { wch: 26 },
    { wch: 24 },
    { wch: 18 },
    { wch: 30 },
    { wch: 42 },
  ];
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, sheet, "Report");
  XLSX.writeFile(workbook, `Customer_Details_Report_${fileDate()}.xlsx`);
};

const escapeHtml = (value: string) => value
  .replaceAll("&", "&amp;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;")
  .replaceAll("'", "&#039;");

export const printCustomerReport = (data: CustomerReportExportData) => {
  const printWindow = window.open("", "_blank", "width=1100,height=760");
  if (!printWindow) throw new Error("The browser blocked the print window.");

  const rows = data.rows.length
    ? data.rows.map((row) => `<tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join("")}</tr>`).join("")
    : `<tr><td colspan="${HEADERS.length}" class="empty">No data</td></tr>`;

  printWindow.document.write(`<!doctype html>
    <html><head><title>Customer Details Report</title><style>
      @page { size: A4 landscape; margin: 18mm; }
      * { box-sizing: border-box; }
      body { margin: 0; color: #111827; font-family: Arial, sans-serif; font-size: 12px; }
      h1 { margin: 0 0 18px; font-size: 22px; }
      p { margin: 4px 0; }
      .filters { margin: 22px 0 16px; }
      table { width: 100%; border-collapse: collapse; table-layout: fixed; }
      th, td { border: 1px solid #dbe2e8; padding: 8px; text-align: left; word-break: break-word; }
      th { background: #2d89be; color: white; font-weight: 600; }
      th:first-child, td:first-child { width: 7%; }
      .empty { height: 48px; text-align: center; color: #64748b; }
    </style></head><body>
      <h1>Customer Details Report</h1>
      <p><strong>Generated on:</strong> ${escapeHtml(data.generatedAt)}</p>
      <p><strong>Generated by:</strong> ${escapeHtml(data.generatedBy)}</p>
      <div class="filters"><p><strong>Applied filters:</strong></p><p>${escapeHtml(filterText(data))}</p></div>
      <table><thead><tr>${HEADERS.map((header) => `<th>${header}</th>`).join("")}</tr></thead><tbody>${rows}</tbody></table>
      <script>window.addEventListener("load", function () { window.print(); });<\/script>
    </body></html>`);
  printWindow.document.close();
};
