import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";

export type GenericReportExportData = {
  title: string;
  generatedAt: string;
  generatedBy: string;
  appliedFilters: string;
  fileNamePrefix: string;
  headers: string[];
  rows: string[][];
};

const fileDate = () => {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const day = String(now.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
};

const escapeHtml = (value: string) =>
  value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");

export const downloadReportPdf = (data: GenericReportExportData) => {
  const pdf = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  pdf.text(data.title, 42, 48);
  pdf.setFontSize(10);
  pdf.text(`Generated on: ${data.generatedAt}`, 42, 76);
  pdf.text(`Generated by: ${data.generatedBy}`, 42, 92);
  pdf.text("Applied filters:", 42, 122);
  pdf.setFont("helvetica", "normal");
  pdf.text(data.appliedFilters, 42, 138);

  const body = data.rows.length
    ? data.rows
    : [[{ content: "No data", colSpan: data.headers.length, styles: { halign: "center" } }]];

  autoTable(pdf, {
    startY: 162,
    head: [data.headers],
    body: body as any,
    theme: "grid",
    styles: {
      fontSize: 8,
      cellPadding: 6,
      lineColor: [220, 226, 232],
      lineWidth: 0.5,
    },
    headStyles: { fillColor: [45, 137, 190], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  pdf.save(`${data.fileNamePrefix}_${fileDate()}.pdf`);
};

export const downloadReportExcel = (data: GenericReportExportData) => {
  const width = Math.max(data.headers.length, 1);
  const sheetRows: (string | number)[][] = [
    [data.title],
    [`Generated on: ${data.generatedAt}`],
    [`Generated by: ${data.generatedBy}`],
    ["Applied filters:"],
    [data.appliedFilters],
    [],
    data.headers,
    ...(data.rows.length
      ? data.rows
      : [Array.from({ length: width }, (_, index) => (index === 0 ? "No data" : ""))]),
  ];

  const sheet = XLSX.utils.aoa_to_sheet(sheetRows);
  const endColumn = String.fromCharCode("A".charCodeAt(0) + Math.max(width - 1, 0));
  sheet["!merges"] = [
    XLSX.utils.decode_range(`A1:${endColumn}1`),
    XLSX.utils.decode_range(`A2:${endColumn}2`),
    XLSX.utils.decode_range(`A3:${endColumn}3`),
    XLSX.utils.decode_range(`A4:${endColumn}4`),
    XLSX.utils.decode_range(`A5:${endColumn}5`),
  ];

  sheet["!cols"] = data.headers.map((header) => ({
    wch: Math.max(12, Math.min(40, header.length + 10)),
  }));

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, sheet, "Report");
  XLSX.writeFile(workbook, `${data.fileNamePrefix}_${fileDate()}.xlsx`);
};

export const printReport = (data: GenericReportExportData) => {
  const printWindow = window.open("", "_blank", "width=1100,height=760");
  if (!printWindow) throw new Error("The browser blocked the print window.");

  const rows = data.rows.length
    ? data.rows
        .map(
          (row) =>
            `<tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join("")}</tr>`,
        )
        .join("")
    : `<tr><td colspan="${data.headers.length}" class="empty">No data</td></tr>`;

  printWindow.document.write(`<!doctype html>
    <html><head><title>${escapeHtml(data.title)}</title><style>
      @page { size: A4 landscape; margin: 18mm; }
      * { box-sizing: border-box; }
      body { margin: 0; color: #111827; font-family: Arial, sans-serif; font-size: 12px; }
      h1 { margin: 0 0 18px; font-size: 22px; }
      p { margin: 4px 0; }
      .filters { margin: 22px 0 16px; }
      table { width: 100%; border-collapse: collapse; table-layout: fixed; }
      th, td { border: 1px solid #dbe2e8; padding: 8px; text-align: left; word-break: break-word; }
      th { background: #2d89be; color: white; font-weight: 600; }
      th:first-child, td:first-child { width: 7%; }
      .empty { height: 48px; text-align: center; color: #64748b; }
    </style></head><body>
      <h1>${escapeHtml(data.title)}</h1>
      <p><strong>Generated on:</strong> ${escapeHtml(data.generatedAt)}</p>
      <p><strong>Generated by:</strong> ${escapeHtml(data.generatedBy)}</p>
      <div class="filters"><p><strong>Applied filters:</strong></p><p>${escapeHtml(data.appliedFilters)}</p></div>
      <table><thead><tr>${data.headers.map((header) => `<th>${escapeHtml(header)}</th>`).join("")}</tr></thead><tbody>${rows}</tbody></table>
      <script>window.addEventListener("load", function () { window.print(); });<\/script>
    </body></html>`);
  printWindow.document.close();
};
